name: Deploy Experimental Stack

on:
  push:
    branches:
      - experimental
  pull_request:
    branches:
      - experimental
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    # This is the magic line that tells GitHub to use your Ziggy runner!
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        run: |
          cd /data/yse_pz/YSE_PZ_experimental
          
          git fetch origin
          git reset --hard origin/experimental
          
          ./venv/bin/pip install wheel
          ./venv/bin/pip install --no-build-isolation "extinction==0.4.2"
          ./venv/bin/pip install "sncosmo==2.8.0" "urllib3<1.27" "django>=3.2,<4.0"
          ./venv/bin/pip install --use-deprecated=legacy-resolver -r requirements.txt
          
          ./venv/bin/python manage.py migrate --noinput --skip-checks
          
          sudo systemctl restart apache2
